/* tslint:disable */
/* eslint-disable */
/**
 * raumreservierung-backend
 * This is the backend-project of the renewal of the raumreservierung
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EquipmentResponseDto
 */
export interface EquipmentResponseDto {
    /**
     * 
     * @type {string}
     * @memberof EquipmentResponseDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentResponseDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentResponseDto
     */
    description: string;
}

/**
 * Check if a given object implements the EquipmentResponseDto interface.
 */
export function instanceOfEquipmentResponseDto(value: object): value is EquipmentResponseDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function EquipmentResponseDtoFromJSON(json: any): EquipmentResponseDto {
    return EquipmentResponseDtoFromJSONTyped(json, false);
}

export function EquipmentResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquipmentResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'description': json['description'],
    };
}

export function EquipmentResponseDtoToJSON(json: any): EquipmentResponseDto {
    return EquipmentResponseDtoToJSONTyped(json, false);
}

export function EquipmentResponseDtoToJSONTyped(value?: EquipmentResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
    };
}

