/* tslint:disable */
/* eslint-disable */
/**
 * raumreservierung-backend
 * This is the backend-project of the renewal of the raumreservierung
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EquipmentRequestDto
 */
export interface EquipmentRequestDto {
    /**
     * 
     * @type {string}
     * @memberof EquipmentRequestDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentRequestDto
     */
    description?: string;
}

/**
 * Check if a given object implements the EquipmentRequestDto interface.
 */
export function instanceOfEquipmentRequestDto(value: object): value is EquipmentRequestDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function EquipmentRequestDtoFromJSON(json: any): EquipmentRequestDto {
    return EquipmentRequestDtoFromJSONTyped(json, false);
}

export function EquipmentRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquipmentRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function EquipmentRequestDtoToJSON(json: any): EquipmentRequestDto {
    return EquipmentRequestDtoToJSONTyped(json, false);
}

export function EquipmentRequestDtoToJSONTyped(value?: EquipmentRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

