/* tslint:disable */
/* eslint-disable */
/**
 * raumreservierung-backend
 * This is the backend-project of the renewal of the raumreservierung
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HolidayRequestDTO
 */
export interface HolidayRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof HolidayRequestDTO
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof HolidayRequestDTO
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof HolidayRequestDTO
     */
    endDate?: Date;
}

/**
 * Check if a given object implements the HolidayRequestDTO interface.
 */
export function instanceOfHolidayRequestDTO(value: object): value is HolidayRequestDTO {
    return true;
}

export function HolidayRequestDTOFromJSON(json: any): HolidayRequestDTO {
    return HolidayRequestDTOFromJSONTyped(json, false);
}

export function HolidayRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): HolidayRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
    };
}

export function HolidayRequestDTOToJSON(json: any): HolidayRequestDTO {
    return HolidayRequestDTOToJSONTyped(json, false);
}

export function HolidayRequestDTOToJSONTyped(value?: HolidayRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'startDate': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString().substring(0,10),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString().substring(0,10),
    };
}

