/* tslint:disable */
/* eslint-disable */
/**
 * raumreservierung-backend
 * This is the backend-project of the renewal of the raumreservierung
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HolidayResponseDTO
 */
export interface HolidayResponseDTO {
    /**
     * 
     * @type {string}
     * @memberof HolidayResponseDTO
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof HolidayResponseDTO
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof HolidayResponseDTO
     */
    endDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof HolidayResponseDTO
     */
    id?: string;
}

/**
 * Check if a given object implements the HolidayResponseDTO interface.
 */
export function instanceOfHolidayResponseDTO(value: object): value is HolidayResponseDTO {
    return true;
}

export function HolidayResponseDTOFromJSON(json: any): HolidayResponseDTO {
    return HolidayResponseDTOFromJSONTyped(json, false);
}

export function HolidayResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): HolidayResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function HolidayResponseDTOToJSON(json: any): HolidayResponseDTO {
    return HolidayResponseDTOToJSONTyped(json, false);
}

export function HolidayResponseDTOToJSONTyped(value?: HolidayResponseDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'startDate': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString().substring(0,10),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString().substring(0,10),
        'id': value['id'],
    };
}

