/* tslint:disable */
/* eslint-disable */
/**
 * raumreservierung-backend
 * This is the backend-project of the renewal of the raumreservierung
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EquipmentRequestDto,
  EquipmentResponseDto,
} from '../models/index';
import {
    EquipmentRequestDtoFromJSON,
    EquipmentRequestDtoToJSON,
    EquipmentResponseDtoFromJSON,
    EquipmentResponseDtoToJSON,
} from '../models/index';

export interface DeleteEquipmentRequest {
    body: string;
}

export interface SaveEquipmentRequest {
    equipmentRequestDto: EquipmentRequestDto;
}

export interface UpdateEquipmentRequest {
    equipmentRequestDto: EquipmentRequestDto;
}

/**
 * 
 */
export class EquipmentControllerApi extends runtime.BaseAPI {

    /**
     * Delete an equipment entity.  Deletes the equipment resource identified by the given UUID.
     * Delete an equipment entity.
     */
    async deleteEquipmentRaw(requestParameters: DeleteEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling deleteEquipment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/equipment`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an equipment entity.  Deletes the equipment resource identified by the given UUID.
     * Delete an equipment entity.
     */
    async deleteEquipment(requestParameters: DeleteEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteEquipmentRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieve all equipment entities.  Returns a list of all existing equipment resources.
     * Retrieve all equipment entities.
     */
    async getAllEquipmentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EquipmentResponseDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/equipment`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EquipmentResponseDtoFromJSON));
    }

    /**
     * Retrieve all equipment entities.  Returns a list of all existing equipment resources.
     * Retrieve all equipment entities.
     */
    async getAllEquipments(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EquipmentResponseDto>> {
        const response = await this.getAllEquipmentsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Create a new equipment entity.  Creates a new equipment resource using the provided details.
     * Create a new equipment entity.
     */
    async saveEquipmentRaw(requestParameters: SaveEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquipmentResponseDto>> {
        if (requestParameters['equipmentRequestDto'] == null) {
            throw new runtime.RequiredError(
                'equipmentRequestDto',
                'Required parameter "equipmentRequestDto" was null or undefined when calling saveEquipment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/equipment`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EquipmentRequestDtoToJSON(requestParameters['equipmentRequestDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquipmentResponseDtoFromJSON(jsonValue));
    }

    /**
     * Create a new equipment entity.  Creates a new equipment resource using the provided details.
     * Create a new equipment entity.
     */
    async saveEquipment(requestParameters: SaveEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquipmentResponseDto> {
        const response = await this.saveEquipmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an existing equipment entity.  Updates an existing equipment resource using the provided details.
     * Update an existing equipment entity.
     */
    async updateEquipmentRaw(requestParameters: UpdateEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquipmentResponseDto>> {
        if (requestParameters['equipmentRequestDto'] == null) {
            throw new runtime.RequiredError(
                'equipmentRequestDto',
                'Required parameter "equipmentRequestDto" was null or undefined when calling updateEquipment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/equipment`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EquipmentRequestDtoToJSON(requestParameters['equipmentRequestDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquipmentResponseDtoFromJSON(jsonValue));
    }

    /**
     * Update an existing equipment entity.  Updates an existing equipment resource using the provided details.
     * Update an existing equipment entity.
     */
    async updateEquipment(requestParameters: UpdateEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquipmentResponseDto> {
        const response = await this.updateEquipmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
