/* tslint:disable */
/* eslint-disable */
/**
 * raumreservierung-backend
 * This is the backend-project of the renewal of the raumreservierung
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HolidayRequestDTO,
  HolidayResponseDTO,
} from '../models/index';
import {
    HolidayRequestDTOFromJSON,
    HolidayRequestDTOToJSON,
    HolidayResponseDTOFromJSON,
    HolidayResponseDTOToJSON,
} from '../models/index';

export interface CreateHolidayRequest {
    holidayRequestDTO: HolidayRequestDTO;
}

export interface DeleteHolidayRequest {
    body: string;
}

export interface UpdateHolidayRequest {
    holidayRequestDTO: HolidayRequestDTO;
}

/**
 * 
 */
export class HolidayControllerApi extends runtime.BaseAPI {

    /**
     */
    async createHolidayRaw(requestParameters: CreateHolidayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HolidayResponseDTO>> {
        if (requestParameters['holidayRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'holidayRequestDTO',
                'Required parameter "holidayRequestDTO" was null or undefined when calling createHoliday().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/holidays`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HolidayRequestDTOToJSON(requestParameters['holidayRequestDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HolidayResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async createHoliday(requestParameters: CreateHolidayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HolidayResponseDTO> {
        const response = await this.createHolidayRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteHolidayRaw(requestParameters: DeleteHolidayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling deleteHoliday().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/holidays`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteHoliday(requestParameters: DeleteHolidayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteHolidayRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getPublicHolidaysRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<HolidayResponseDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/holidays/public`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(HolidayResponseDTOFromJSON));
    }

    /**
     */
    async getPublicHolidays(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<HolidayResponseDTO>> {
        const response = await this.getPublicHolidaysRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getSchoolHolidaysRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<HolidayResponseDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/holidays/school`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(HolidayResponseDTOFromJSON));
    }

    /**
     */
    async getSchoolHolidays(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<HolidayResponseDTO>> {
        const response = await this.getSchoolHolidaysRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async updateHolidayRaw(requestParameters: UpdateHolidayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HolidayResponseDTO>> {
        if (requestParameters['holidayRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'holidayRequestDTO',
                'Required parameter "holidayRequestDTO" was null or undefined when calling updateHoliday().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/holidays`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: HolidayRequestDTOToJSON(requestParameters['holidayRequestDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HolidayResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async updateHoliday(requestParameters: UpdateHolidayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HolidayResponseDTO> {
        const response = await this.updateHolidayRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
