export const ROUTES = {
  HOME: "home",
  GETSTARTED: "getstarted",
  EQUIPMENT: "equipment",
  SEATING: "seating",
  HELP: "help",
  INTERNAL_PERSON: "internal_person",
  EXTERNAL_PERSON: "external_person",
  PUBLIC_HOLIDAYS: "public_holidays",
  SCHOOL_HOLIDAYS: "school_holidays",
  ROOMS_LIST: "rooms_list",
  ROOMS_DETAILS: "rooms_details",
  ROOMS_EDIT: "rooms_edit",
  ROOMS_CREATE: "rooms_create",
} as const;
